#!/usr/bin/env python3
"""Draws the app icon, everywhere it is needed, from one description of it.

    python3 tools/make-icons.py

The old icon was a terrain profile with a charge curve falling across it: four
and five pixel strokes in muted grey and blue on an off-white ground. At the
size a launcher actually draws it — 48dp, and an adaptive icon crops to a
circle inside that — the lines thinned to nothing and the whole thing read as a
smudge. It was a picture of what the app does, at a size where a picture cannot
be read.

This is one shape instead: an S bent like a ghat road, white on the brand
green. It is the initial of the name and the shape of the road the app is for,
and it survives being 48 pixels wide, which is the only test that matters.

No imaging library — the machine has none, and an icon generator that needs one
installed is a generator nobody runs. The curve is stroked by stamping a disc
along it, which is exactly what a round cap and join are, and the whole thing is
drawn at four times the size and averaged down for the edges.
"""
import struct, zlib, pathlib, sys

GREEN = (0x1D, 0x87, 0x24)          # --brand-green, light theme
WHITE = (0xFF, 0xFF, 0xFF)

# The road, in a 108-unit box — the Android adaptive icon's viewport. Content
# keeps inside the middle 66 units, because that circle is all a launcher is
# guaranteed to show.
STROKE = 12.5

# A road narrows as it goes away from you, and that is the one way to say
# "road" that survives being 48 pixels wide: it changes the silhouette, and a
# silhouette is what downscaling leaves you. A dashed centre line says it far
# more plainly at 512 and breaks the letter into a chain at 48 — rendered,
# looked at, discarded.
WIDE, NARROW = 1.45, 0.62          # stroke scale at the near and far ends
CURVES = [
    ((70.0, 33.0), (70.0, 22.5), (41.0, 23.0), (41.0, 39.0)),
    ((41.0, 39.0), (41.0, 52.5), (68.0, 55.5), (68.0, 70.0)),
    ((68.0, 70.0), (68.0, 85.0), (39.0, 85.5), (38.5, 75.0)),
]


def bezier(p0, p1, p2, p3, t):
    u = 1 - t
    return (u*u*u*p0[0] + 3*u*u*t*p1[0] + 3*u*t*t*p2[0] + t*t*t*p3[0],
            u*u*u*p0[1] + 3*u*u*t*p1[1] + 3*u*t*t*p2[1] + t*t*t*p3[1])


def road(steps=600):
    """The centreline, and how wide the road is at each point along it."""
    pts = []
    for c in CURVES:
        pts += [bezier(*c, i / steps) for i in range(steps + 1)]
    last = len(pts) - 1
    return [(p, STROKE * (NARROW + (WIDE - NARROW) * i / last))
            for i, p in enumerate(pts)]


def render(size, bg, fg, ss=4):
    """The icon at `size`, supersampled by `ss` and averaged down."""
    n = size * ss
    scale = n / 108.0
    ink = bytearray([0]) * (n * n)          # coverage mask

    for ((x, y), w) in road():
        cx, cy = x * scale, y * scale
        r = w / 2 * scale
        r2 = r * r
        x0, x1 = max(0, int(cx - r) - 1), min(n - 1, int(cx + r) + 1)
        y0, y1 = max(0, int(cy - r) - 1), min(n - 1, int(cy + r) + 1)
        for yy in range(y0, y1 + 1):
            dy = yy + 0.5 - cy
            dy2 = dy * dy
            if dy2 > r2:
                continue
            row = yy * n
            for xx in range(x0, x1 + 1):
                dx = xx + 0.5 - cx
                if dx * dx + dy2 <= r2:
                    ink[row + xx] = 1

    out = bytearray()
    for y in range(size):
        out.append(0)                        # PNG filter: none
        for x in range(size):
            hit = 0
            for sy in range(ss):
                row = (y * ss + sy) * n + x * ss
                for sx in range(ss):
                    hit += ink[row + sx]
            a = hit / (ss * ss)
            out += bytes(int(bg[i] + (fg[i] - bg[i]) * a + 0.5) for i in range(3))
    return bytes(out)


def write_png(path, size, raw):
    def chunk(t, d):
        return (struct.pack('>I', len(d)) + t + d
                + struct.pack('>I', zlib.crc32(t + d) & 0xffffffff))
    png = (b'\x89PNG\r\n\x1a\n'
           + chunk(b'IHDR', struct.pack('>IIBBBBB', size, size, 8, 2, 0, 0, 0))
           + chunk(b'IDAT', zlib.compress(bytes(raw), 9))
           + chunk(b'IEND', b''))
    pathlib.Path(path).write_bytes(png)
    print(f'  {path}  {size}x{size}  {len(png)/1024:.1f} KB')


VECTOR = '''<?xml version="1.0" encoding="utf-8"?>
<!-- The road as an S, and the S as a road. A filled outline rather than a
     stroked line, because the road narrows as it recedes and a vector stroke
     has one width for its whole length. Generated by tools/make-icons.py from
     the same curve the store icons are drawn from. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp" android:height="108dp"
    android:viewportWidth="108" android:viewportHeight="108">
    <path android:pathData="%s" android:fillColor="#FFFFFF" />
</vector>
'''


def outline(step=6, cap=14):
    """The tapered road as a closed boundary: up one verge and back the other.

    Every point is walked twice — once offset to the left of the centreline and
    once to the right — with a fan of points at each end for the round cap. It
    is a polygon rather than curves, which makes for a long path string and an
    exactly right shape; the alternative is fitting beziers to an offset curve,
    which is a great deal of arithmetic to arrive somewhere no crisper.
    """
    import math
    pts = road()
    left, right = [], []
    for i, ((x, y), w) in enumerate(pts):
        if i % step and 0 < i < len(pts) - 1:
            continue
        j = min(len(pts) - 1, i + 1) if i < len(pts) - 1 else i
        k = max(0, i - 1)
        tx, ty = pts[j][0][0] - pts[k][0][0], pts[j][0][1] - pts[k][0][1]
        m = math.hypot(tx, ty) or 1.0
        nx, ny = -ty / m, tx / m
        r = w / 2
        left.append((x + nx * r, y + ny * r))
        right.append((x - nx * r, y - ny * r))

    def arc(centre, radius, frm, to):
        return [(centre[0] + radius * math.cos(frm + (to - frm) * i / cap),
                 centre[1] + radius * math.sin(frm + (to - frm) * i / cap))
                for i in range(cap + 1)]

    def ang(a, b):
        return math.atan2(b[1] - a[1], b[0] - a[0])

    (p_end, w_end) = pts[-1]
    (p_start, w_start) = pts[0]
    a_end = ang(pts[-2][0], p_end)
    a_start = ang(pts[1][0], p_start)

    ring = (left
            + arc(p_end, w_end / 2, a_end + math.pi / 2, a_end - math.pi / 2)
            + right[::-1]
            + arc(p_start, w_start / 2, a_start - math.pi / 2, a_start + math.pi / 2))

    d = f'M{ring[0][0]:.2f},{ring[0][1]:.2f}'
    d += ''.join(f'L{x:.2f},{y:.2f}' for (x, y) in ring[1:])
    return d + 'Z'


def outline_agrees(size=256, tol=0.006):
    """Does the polygon the launcher will fill match the shape drawn for the
    stores?

    Two renderers of one road: discs stamped along the centreline for the
    pixels, and an offset boundary for the vector. They are different arithmetic
    and they can disagree — an inverted normal or a cap on backwards gives a
    polygon that still looks like something, and the only place it would show up
    is on a phone. So the polygon is scan-filled here and compared against the
    raster, and a disagreement stops the build rather than shipping.
    """
    import re
    d = outline()
    ring = [tuple(map(float, m)) for m in
            re.findall(r'[ML](-?[\d.]+),(-?[\d.]+)', d)]
    sc = size / 108.0
    poly = [(x * sc, y * sc) for (x, y) in ring]

    filled = bytearray(size * size)
    for y in range(size):
        yc = y + 0.5
        xs = []
        for i in range(len(poly)):
            (x1, y1), (x2, y2) = poly[i], poly[(i + 1) % len(poly)]
            if (y1 <= yc) != (y2 <= yc):
                xs.append(x1 + (yc - y1) * (x2 - x1) / (y2 - y1))
        xs.sort()
        for i in range(0, len(xs) - 1, 2):
            for x in range(max(0, int(xs[i] + 0.5)), min(size, int(xs[i + 1] + 0.5))):
                filled[y * size + x] = 1

    raw = render(size, (0, 0, 0), (255, 255, 255), ss=2)
    stride = size * 3 + 1
    diff = 0
    for y in range(size):
        row = y * stride + 1
        for x in range(size):
            a = 1 if raw[row + x * 3] > 127 else 0
            if a != filled[y * size + x]:
                diff += 1
    share = diff / (size * size)
    print(f'  outline vs raster: {share*100:.2f}% pixels differ')
    return share <= tol


if __name__ == '__main__':
    root = pathlib.Path(__file__).resolve().parent.parent

    if not outline_agrees():
        raise SystemExit('the vector outline does not match the drawn icon — '
                         'the launcher would show a different shape')

    # Android: a vector foreground on a flat green background layer.
    (root / 'app/src/main/res/drawable/ic_launcher_foreground.xml').write_text(
        VECTOR % outline(), encoding='utf-8')
    print('  app/src/main/res/drawable/ic_launcher_foreground.xml')

    # Everywhere that wants pixels. The adaptive icon crops; these do not, so
    # they are drawn from the same curve at the same proportions.
    for path, size in (('web/icons/icon-192.png', 192),
                       ('web/icons/icon-512.png', 512),
                       ('web/icons/icon-1024-playstore.png', 1024),
                       ('ios/Assets.xcassets/AppIcon.appiconset/icon-1024.png', 1024)):
        ss = 4 if size <= 512 else 2         # 1024 at 4x is a lot of pixels
        write_png(root / path, size, render(size, GREEN, WHITE, ss))
